import cardAceOfHearts from './Assets/Ace-Hearts.png';
import cardKingOfHearts from './Assets/King-Hearts.png';
import cardQueenOfHearts from './Assets/Queen-Hearts.png';
import cardJackOfHearts from './Assets/Jack-Hearts.png';
import card2OfHearts from './Assets/2-Hearts.png';
import card3OfHearts from './Assets/3-Hearts.png';
import card4OfHearts from './Assets/4-Hearts.png';
import card5OfHearts from './Assets/5-Hearts.png';
import card6OfHearts from './Assets/6-Hearts.png';
import card7OfHearts from './Assets/7-Hearts.png';
import card8OfHearts from './Assets/8-Hearts.png';
import card9OfHearts from './Assets/9-Hearts.png';
import card10OfHearts from './Assets/10-Hearts.png';
import cardAceOfDiamonds from './Assets/Ace-Diamonds.png';
import cardKingOfDiamonds from './Assets/King-Diamonds.png';
import cardQueenOfDiamonds from './Assets/Queen-Diamonds.png';
import cardJackOfDiamonds from './Assets/Jack-Diamonds.png';
import card2OfDiamonds from './Assets/2-Diamonds.png';
import card3OfDiamonds from './Assets/3-Diamonds.png';
import card4OfDiamonds from './Assets/4-Diamonds.png';
import card5OfDiamonds from './Assets/5-Diamonds.png';
import card6OfDiamonds from './Assets/6-Diamonds.png';
import card7OfDiamonds from './Assets/7-Diamonds.png';
import card8OfDiamonds from './Assets/8-Diamonds.png';
import card9OfDiamonds from './Assets/9-Diamonds.png';
import card10OfDiamonds from './Assets/10-Diamonds.png';
import cardAceOfSpades from './Assets/Ace-Spades.png';
import cardKingOfSpades from './Assets/King-Spades.png';
import cardQueenOfSpades from './Assets/Queen-Spades.png';
import cardJackOfSpades from './Assets/Jack-Spades.png';
import card2OfSpades from './Assets/2-Spades.png';
import card3OfSpades from './Assets/3-Spades.png';
import card4OfSpades from './Assets/4-Spades.png';
import card5OfSpades from './Assets/5-Spades.png';
import card6OfSpades from './Assets/6-Spades.png';
import card7OfSpades from './Assets/7-Spades.png';
import card8OfSpades from './Assets/8-Spades.png';
import card9OfSpades from './Assets/9-Spades.png';
import card10OfSpades from './Assets/10-Spades.png';
import cardAceOfClubs from './Assets/Ace-Clubs.png';
import cardKingOfClubs from './Assets/King-Clubs.png';
import cardQueenOfClubs from './Assets/Queen-Clubs.png';
import cardJackOfClubs from './Assets/Jack-Clubs.png';
import card2OfClubs from './Assets/2-Clubs.png';
import card3OfClubs from './Assets/3-Clubs.png';
import card4OfClubs from './Assets/4-Clubs.png';
import card5OfClubs from './Assets/5-Clubs.png';
import card6OfClubs from './Assets/6-Clubs.png';
import card7OfClubs from './Assets/7-Clubs.png';
import card8OfClubs from './Assets/8-Clubs.png';
import card9OfClubs from './Assets/9-Clubs.png';
import card10OfClubs from './Assets/10-Clubs.png';

// let importCode = "";
// let deck = new Deck();
// deck.cards.forEach((card, idx) => {
//   if (idx <=30 )
//   importCode += `import card${card.value}Of${card.suit} from './Assets/${card.value}-${card.suit}.png';
//   `;
// });
// console.dir(importCode);
